// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqF89Sg5r9hIkBMP8mePpvTXL7aTzbbfc',
    appId: '1:63816105500:web:5a386eb1cae1e0bc58e9d9',
    messagingSenderId: '63816105500',
    projectId: 'raidtraintv',
    authDomain: 'raidtraintv.firebaseapp.com',
    databaseURL: 'https://raidtraintv-default-rtdb.firebaseio.com',
    storageBucket: 'raidtraintv.appspot.com',
    measurementId: 'G-6LYQ401Z5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6YfCCGP3ZquxlgtYc773BZ3Srdi1Whf4',
    appId: '1:63816105500:android:12a973ffb5801b5c58e9d9',
    messagingSenderId: '63816105500',
    projectId: 'raidtraintv',
    databaseURL: 'https://raidtraintv-default-rtdb.firebaseio.com',
    storageBucket: 'raidtraintv.appspot.com',
  );
}
