name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Get dependencies with Flutter pub
      - run: flutter pub get

      # Build the web project with Flutter (Build should also run tests)
      - run: flutter build web
